config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
Rails.application.routes.draw do
  start = Time.zone.now

  # Routes only accessible by admins (admin panels, sidekiq, pghero)
  authenticate :user, ->(user) { user.has_role?(:administrator) } do
    # Admin panel
    mount RailsAdmin::Engine => "/justask_admin", :as => "rails_admin"

    mount Sidekiq::Web, at: "/sidekiq"
    mount PgHero::Engine, at: "/pghero", as: "pghero"
  end

  root to: "about#index"

  get "/about", to: "about#about"
  get "/privacy", to: "about#privacy_policy", as: :privacy_policy
  get "/terms", to: "about#terms", as: :terms
  get "/linkfilter", to: "link_filter#index", as: :linkfilter
  get "/manifest.json", to: "manifests#show", as: :webapp_manifest

  constraints(Constraints::LocalNetwork) do
    get "/metrics", to: "metrics#show"
  end

  # Devise routes
  devise_for :users, path: "user", skip: %i[sessions registrations]
  as :user do
    # :sessions
    get "sign_in" => "user/sessions#new", :as => :new_user_session
    post "sign_in" => "user/sessions#create", :as => :user_session
    delete "sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    # :registrations
    get "settings/delete_account" => "devise/registrations#cancel", :as => :cancel_user_registration
    get "/settings/account" => "devise/registrations#edit", :as => :edit_user_registration
    patch "/settings/account" => "devise/registrations#update", :as => :update_user_registration
    put "/settings/account" => "devise/registrations#update"
    delete "/settings/account" => "user/registrations#destroy"
  end

  namespace :settings do
    get :export, to: "export#index"
    post :export, to: "export#create"
  end

  resource :anonymous_block, controller: :anonymous_block, only: %i[create destroy]

  namespace :well_known, path: "/.well-known" do
    get "/change-password", to: redirect("/settings/account")
    get "/nodeinfo", to: "node_info#discovery"
  end

  get "/nodeinfo/2.1", to: "well_known/node_info#nodeinfo", as: :node_info

  get "/modal/close", to: "modal#close", as: :modal_close

  puts "processing time of routes.rb: #{"#{(Time.zone.now - start).round(3).to_s.ljust(5, '0')}s".light_green}"
end

app/models/reports/user.rb
class Reports::User < Report
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include ActiveModel::OneTimePassword

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :async, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, authentication_keys: [:login]

  has_one_time_password
  enum otp_module: { disabled: 0, enabled: 1 }, _prefix: true
  attr_accessor :otp_attempt, :otp_validation
  attr_writer :login

  rolify

  has_many :totp_recovery_codes, dependent: :destroy_async

  has_one :profile, dependent: :destroy

  SCREEN_NAME_REGEX = /\A[a-zA-Z0-9_]+\z/
  WEBSITE_REGEX = /https?:\/\/([A-Za-z.-]+)\/?(?:.*)/i

  before_validation do
    screen_name.strip!
  end

  validates :email, fake_email: true, typoed_email: true
  validates :sharing_custom_url, allow_blank: true, valid_url: true
  validates :screen_name,
            presence:    true,
            format:      { with: SCREEN_NAME_REGEX, message: I18n.t("activerecord.validation.user.screen_name.format") },
            length:      { minimum: 1, maximum: 16 },
            uniqueness:  { case_sensitive: false },
            screen_name: true

  mount_uploader :profile_picture, ProfilePictureUploader, mount_on: :profile_picture_file_name
  process_in_background :profile_picture
  mount_uploader :profile_header, ProfileHeaderUploader, mount_on: :profile_header_file_name
  process_in_background :profile_header

  after_destroy do
    Retrospring::Metrics::USERS_DESTROYED.increment
  end

  after_create do
    Profile.create(user_id: id) if Profile.where(user_id: id).count.zero?

    Retrospring::Metrics::USERS_CREATED.increment
  end

  # use the screen name as parameter for url helpers
  def to_param = screen_name

  def login = @login || screen_name || email

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions).where(["lower(screen_name) = :value OR lower(email) = :value", { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end

  # @return [Boolean] is the user a moderator?
  def mod? = has_cached_role?(:moderator) || has_cached_role?(:administrator)

  def admin? = has_cached_role?(:administrator)
end

app/models/user/answer_methods.rb
# frozen_string_literal: true

module User::AnswerMethods
  include CursorPaginatable

  define_cursor_paginator :cursored_answers, :ordered_answers

  # @return [ActiveRecord::Relation<Answer>] List of a user's answers
  def ordered_answers(current_user_id:)
    answers
      .for_user(current_user_id)
      .order(:created_at)
      .reverse_order
      .includes(question: { user: [:profile] })
  end
end

app/models/user/ban_methods.rb
# frozen_string_literal: true

module User::BanMethods
  def permanently_banned?
    bans.current.first&.permanent? || false
  end

  def banned?
    Rails.cache.fetch("#{cache_key}/banned", expires_in: 6.hours) do
      bans.current.count.positive?
    end
  end

  def unban
    bans.current.update(
      # -1s to account for flakyness with timings in tests
      expires_at: DateTime.now.utc - 1.second,
    )
    Rails.cache.delete("#{cache_key}/banned")
  end

  # Bans a user.
  # @param expiry [DateTime, nil] the expiry time of the ban
  # @param reason [String, nil] Reason for the ban. This is displayed to the user.
  # @param banned_by [User] User who instated the ban
  def ban(expiry = nil, reason = nil, banned_by = nil)
    ::UserBan.create!(
      user:       self,
      expires_at: expiry,
      banned_by:,
      reason:,
    )
    Rails.cache.delete("#{cache_key}/banned")
  end
end

app/models/user/data_export.rb
# frozen_string_literal: true

# stub model to nicely allow for data export notifications, do NOT use this directly!
class User::DataExport < User
end

app/models/user/expired_service_connection.rb
# frozen_string_literal: true

# stub model for notifying about expired service connections
class User::ExpiredServiceConnection < User
end

app/models/user/expired_twitter_service_connection.rb
# frozen_string_literal: true

class User::ExpiredTwitterServiceConnection < User::ExpiredServiceConnection
end

app/models/user/inbox_methods.rb
# frozen_string_literal: true

module User::InboxMethods
  def unread_inbox_count
    Rails.cache.fetch(inbox_cache_key, expires_in: 12.hours) do
      count = InboxEntry.where(new: true, user_id: id).count(:id)

      # Returning +nil+ here in order to not display a counter
      # at all when there isn't anything in the user's inbox
      return nil unless count.positive?

      count
    end
  end

  def inbox_cache_key = "#{cache_key}/unread_inbox_count-#{inbox_updated_at}"
end

app/models/user/notification_methods.rb
# frozen_string_literal: true

module User::NotificationMethods
  def unread_notification_count
    Rails.cache.fetch(notification_cache_key, expires_in: 12.hours) do
      count = Notification.for(self).where(new: true).count(:id)

      # Returning +nil+ here in order to not display a counter
      # at all when there aren't any notifications
      return nil unless count.positive?

      count
    end
  end

  def notification_cache_key = "#{cache_key}/unread_notification_count-#{notifications_updated_at}"
  def notification_dropdown_cache_key = "#{cache_key}/notification_dropdown-#{notifications_updated_at}"
end

app/models/user/push_notification_methods.rb
# frozen_string_literal: true

module User::PushNotificationMethods
  def push_notification(app, resource)
    raise ArgumentError("Resource must respond to `as_push_notification`") unless resource.respond_to? :as_push_notification

    web_push_subscriptions.active.find_each do |s|
      n = Rpush::Webpush::Notification.new
      n.app = app
      n.registration_ids = [s.subscription.symbolize_keys]
      n.data = {
        message: resource.as_push_notification.merge(notification_data).to_json,
      }
      n.save!

      PushNotificationWorker.perform_async(n.id)
    end
  end

  def notification_data = {
    data: {
      badge: unread_inbox_count,
    },
  }
end

app/models/user/question_methods.rb
# frozen_string_literal: true

module User::QuestionMethods
  include CursorPaginatable

  define_cursor_paginator :cursored_questions, :ordered_questions

  # @return [ActiveRecord::Relation<Question>] List of questions sent by the user
  def ordered_questions(author_is_anonymous: nil, direct: nil)
    questions
      .where({ author_is_anonymous:, direct: }.compact)
      .order(:created_at)
      .reverse_order
  end
end

app/models/user/reaction_methods.rb
# frozen_string_literal: true

module User::ReactionMethods
  # smiles an answer or comment
  # @param item [ApplicationRecord] the answer/comment to smile
  def smile(item)
    raise Errors::ReactingSelfBlockedOther if self.blocking?(item.user)
    raise Errors::ReactingOtherBlockedSelf if item.user.blocking?(self)

    Reaction.create!(user: self, parent: item, content: "🙂")
  end

  # unsmile an answer or comment
  # @param item [ApplicationRecord] the answer/comment to unsmile
  def unsmile(item)
    Reaction.find_by!(user: self, parent: item).destroy
  end

  def smiled?(item)
    item.smiles.pluck(:user_id).include? id
  end
end

app/models/user/relationship.rb
# frozen_string_literal: true

class User
  module Relationship
    extend ActiveSupport::Concern

    private

    # Create a relationship for `type` with `target_user` as target.
    def create_relationship(type, target_user)
      type.create(target: target_user)
    end

    # Destroy a relationship for `type` with `target_user` as target.
    def destroy_relationship(type, target_user)
      type.find_by(target: target_user)&.destroy
    end

    def relationship_active?(type, target_user)
      type.include?(target_user)
    end
  end
end

app/models/user/relationship/block.rb
# frozen_string_literal: true

class User
  module Relationship
    module Block
      extend ActiveSupport::Concern

      included do
        has_many :active_block_relationships, class_name:  "Relationships::Block",
                                              foreign_key: "source_id",
                                              dependent:   :destroy
        has_many :passive_block_relationships, class_name:  "Relationships::Block",
                                               foreign_key: "target_id",
                                               dependent:   :destroy
        has_many :blocked_users,    through: :active_block_relationships, source: :target
        has_many :blocked_by_users, through: :passive_block_relationships, source: :source
      end

      # Block an user
      def block(target_user)
        raise Errors::BlockingSelf if target_user == self

        unfollow_and_remove(target_user)
        create_relationship(active_block_relationships, target_user).tap do
          expire_blocked_user_ids_cache
        end
      end

      # Unblock an user
      def unblock(target_user)
        destroy_relationship(active_block_relationships, target_user).tap do
          expire_blocked_user_ids_cache
        end
      end

      # Is <tt>self</tt> blocking <tt>target_user</tt>?
      def blocking?(target_user)
        relationship_active?(blocked_users, target_user)
      end

      # Expire the blocked user ids cache
      def expire_blocked_user_ids_cache = Rails.cache.delete(cache_key_blocked_user_ids)

      # Cached ids of the blocked users
      def blocked_user_ids_cached
        Rails.cache.fetch(cache_key_blocked_user_ids, expires_in: 1.hour) do
          blocked_user_ids
        end
      end

      private

      def unfollow_and_remove(target_user)
        unfollow(target_user) if following?(target_user)
        target_user.unfollow(self) if target_user.following?(self)
        target_user.inbox_entries.joins(:question).where(question: { user_id: id }).destroy_all
        inbox_entries.joins(:question).where(questions: { user_id: target_user.id, author_is_anonymous: false }).destroy_all
        ListMember.joins(:list).where(list: { user_id: target_user.id }, user_id: id).destroy_all
      end

      def cache_key_blocked_user_ids = "#{cache_key}/blocked_user_ids"
    end
  end
end

app/models/user/relationship/follow.rb
# frozen_string_literal: true

class User
  module Relationship
    module Follow
      extend ActiveSupport::Concern

      included do
        has_many :active_follow_relationships, class_name:  "Relationships::Follow",
                                               foreign_key: "source_id",
                                               dependent:   :destroy
        has_many :passive_follow_relationships, class_name:  "Relationships::Follow",
                                                foreign_key: "target_id",
                                                dependent:   :destroy
        has_many :followings, through: :active_follow_relationships, source: :target
        has_many :followers,  through: :passive_follow_relationships, source: :source
      end

      # Follow an user
      def follow(target_user)
        raise Errors::FollowingSelf if target_user == self
        raise Errors::FollowingOtherBlockedSelf if target_user.blocking?(self)
        raise Errors::FollowingSelfBlockedOther if self.blocking?(target_user)

        create_relationship(active_follow_relationships, target_user)
      end

      # Unfollow an user
      def unfollow(target_user)
        destroy_relationship(active_follow_relationships, target_user)
      end

      def following?(target_user)
        relationship_active?(followings, target_user)
      end
    end
  end
end

app/models/user/relationship/mute.rb
# frozen_string_literal: true

class User
  module Relationship
    module Mute
      extend ActiveSupport::Concern

      included do
        has_many :active_mute_relationships, class_name:  "Relationships::Mute",
                                             foreign_key: "source_id",
                                             dependent:   :destroy
        has_many :passive_mute_relationships, class_name:  "Relationships::Mute",
                                              foreign_key: "target_id",
                                              dependent:   :destroy
        has_many :muted_users, through: :active_mute_relationships, source: :target
        has_many :muted_by_users, through: :passive_mute_relationships, source: :source
      end

      # Mute a user
      def mute(target_user)
        raise Errors::MutingSelf if target_user == self

        create_relationship(active_mute_relationships, target_user).tap do
          expire_muted_user_ids_cache
        end
      end

      # Unmute an user
      def unmute(target_user)
        destroy_relationship(active_mute_relationships, target_user).tap do
          expire_muted_user_ids_cache
        end
      end

      # Is <tt>self</tt> muting <tt>target_user</tt>?
      def muting?(target_user)
        relationship_active?(muted_users, target_user)
      end

      # Expires the muted user ids cache
      def expire_muted_user_ids_cache = Rails.cache.delete(cache_key_muted_user_ids)

      # Cached ids of the muted users
      def muted_user_ids_cached
        Rails.cache.fetch(cache_key_muted_user_ids, expires_in: 1.hour) do
          muted_user_ids
        end
      end

      private

      # Cache key for the muted_user_ids
      def cache_key_muted_user_ids = "#{cache_key}/muted_user_ids"
    end
  end
end

app/models/user/relationship_methods.rb
# frozen_string_literal: true

module User::RelationshipMethods
  include CursorPaginatable

  define_cursor_paginator :cursored_following_relationships, :ordered_following_relationships
  define_cursor_paginator :cursored_follower_relationships, :ordered_follower_relationships

  # @return [ActiveRecord::Relation<Relationships::Follow>] List of the user's following relationships
  def ordered_following_relationships
    active_follow_relationships.reverse_order.includes(target: [:profile])
  end

  # @return [ActiveRecord::Relation<Relationships::Follow>] List of the user's follower relationships
  def ordered_follower_relationships
    passive_follow_relationships.reverse_order.includes(source: [:profile])
  end
end

app/models/user/sharing_methods.rb
# frozen_string_literal: true

module User::SharingMethods
  def display_sharing_custom_url
    URI(sharing_custom_url).host
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :redirect_if_registrations_disabled!, only: %w[create new] # rubocop:disable Rails/LexicallyScopedActionFilter

  def destroy
    # TODO: destroy export async
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    resource.destroy
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
  end

  private

  def captcha_valid?
    # If the captcha isn't enabled, treat it as being correct
    return true unless APP_CONFIG.dig(:hcaptcha, :enabled)

    verify_hcaptcha
  end

  def redirect_if_registrations_disabled!
    redirect_to root_path
  end
end

app/views/user/_actions.html.haml
.profile__actions
  - type ||= :nil
  - own_followings ||= nil
  - own_blocks ||= nil
  - own_mutes ||= nil
  - if user_signed_in? && user == current_user
    .d-grid
      %a.btn.btn-dark{ href: settings_profile_path } Edit profile
  - elsif user_signed_in?
    .d-grid.gap-2
      - if own_followings&.include?(user.id) || current_user.following?(user)
        = render "relationships/destroy", type: "follow", screen_name: user.screen_name
      - else
        = render "relationships/create", type: "follow", screen_name: user.screen_name
      .btn-group
        %button.btn.btn-light.btn-sm.dropdown-toggle{ data: { bs_toggle: :dropdown }, aria: { expanded: false } }
          = t(".title")
          %span.caret
        .dropdown-menu
          %a.dropdown-item.d-block.d-sm-none{ href: '#', data: { bs_target: '#modal-list-memberships', bs_toggle: :modal } }
            %i.fa.fa-list.fa-fw
            = t(".list")
          - if own_blocks&.include?(user.id) || current_user.blocking?(user)
            = render "relationships/destroy", type: "block", screen_name: user.screen_name
          - else
            = render "relationships/create", type: "block", screen_name: user.screen_name
          - if own_mutes&.include?(user.id) || current_user.muting?(user)
            = render "relationships/destroy", type: "mute", screen_name: user.screen_name
          - else
            = render "relationships/create", type: "mute", screen_name: user.screen_name
          %a.dropdown-item{ href: '#', data: { action: 'report-user', target: user.screen_name } }
            %i.fa.fa-exclamation-triangle.fa-fw
            = t("voc.report")
          - if current_user.mod?
            %a.dropdown-item{ href: moderation_reports_path(user: user.screen_name) }
              %i.far.fa-flag.fa-fw
              = t(".reports_from", user: user.screen_name)
            %a.dropdown-item{ href: moderation_reports_path(target_user: user.screen_name) }
              %i.fas.fa-flag.fa-fw
              = t(".reports_of", user: user.screen_name)
            %a.dropdown-item{ href: '#', data: { bs_target: '#modal-privileges', bs_toggle: :modal } }
              %i.fa.fa-wrench.fa-fw
              = t(".privilege", user: user.screen_name)
            - unless user.has_cached_role?(:administrator)
              %a.dropdown-item{ href: '#', data: { bs_target: '#modal-ban', bs_toggle: :modal } }
                %i.fa.fa-ban.fa-fw
                = t(".ban")
          - if current_user.mod? && user != current_user
            %a.dropdown-item{ href: mod_inbox_index_path(user: user.screen_name) }
              %i.fa.fa-inbox.fa-fw
              = t(".view_inbox")
          - if current_user.has_cached_role? :administrator
            %a.dropdown-item{ href: rails_admin_path_for_resource(user), target: '_blank' }
              %i.fa.fa-cogs.fa-fw
              = t("voc.view_in_rails_admin")

app/views/user/_modal_ban.html.haml
#modal-ban.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal-ban-label", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4#modal-ban-label.modal-title
          = t 'views.modal.bancontrol.title'
      = bootstrap_form_tag(url: '/mod/ban', html: { method: :post, novalidate: "novalidate" }) do |f|
        = f.hidden_field :user, value: @user.screen_name
        #ban-control-super.modal-body
          = f.check_box :ban, label: t('views.modal.bancontrol.ban'), checked: @user.banned?
          #ban-controls{style: "#{"display: none" unless @user.banned?}"}
            = f.check_box :permaban, label: t('views.modal.bancontrol.permanent'), checked: @user.permanently_banned?
            #ban-controls-time{style: "#{"display: none" unless not @user.permanently_banned?}"}
              = f.text_field :until, label: "", required: true, value: (@user.banned_until || DateTime.current).strftime("%m/%d/%Y %I:%M %p")
            = f.text_field :reason, placeholder: t('views.modal.bancontrol.reason'), value: @user.ban_reason
        .modal-footer
          %button.btn.btn-default{name: 'stop-time', type: :button, data: { dismiss: :modal }}= t 'views.actions.close'
          = f.submit t('views.modal.bancontrol.hammertime'), class: "btn btn-primary", name: 'hammer-time'

app/views/user/_modal_group_item.html.haml
%li.list-group-item{id: "group-#{group.name}"}
  .media
    .pull-left.j2-table
      %input.input--center{type: :checkbox, name: 'gm-group-check', data: { group: group.name, user: user.screen_name }, checked: user.member_of?(group), autocomplete: 'off'}
    .media-body
      .list-group-item-heading= group.display_name
      .list-group-item-text.text-muted.j2-up
        %span{id: "#{group.name}-members"}= group.members.count
        = t 'views.modal.group.members'
        ·
        %a.j2-delete#delete-group{href: "#", data: { group: group.name }}
          %i.fa.fa-close
          = t 'views.actions.delete'

app/views/user/_modal_group_memberships.html.haml
#modal-group-memberships.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal-group-memberships-label", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only= t 'views.actions.close'
        %h4#modal-group-memberships-label.modal-title= t 'views.modal.group.title'
      %div{role: "tabpanel"}
        %ul.nav.nav-tabs{role: "tablist"}
          %li.active{role: "presentation"}
            %a{href: "#grouplist", aria: {controls: "grouplist"}, data: {toggle: "tab"}, role: "tab"}
              = t 'views.modal.group.tabs.main'
          %li{role: "presentation"}
            %a{href: "#create", aria: {controls: "create"}, data: {toggle: "tab"}, role: "tab"}
              = t 'views.modal.group.tabs.create'

        .tab-content
          .tab-pane.active{role:"tabpanel", id: "grouplist"}
            %ul.list-group.groups--list
              - current_user.groups.each do |group|
                = render 'user/modal_group_item', group: group, user: @user
          .tab-pane{role:"tabpanel", id: "create"}
            .modal-body
              %input#new-group-name.form-control{type: :text, placeholder: t('views.modal.group.name')}
              %button#create-group.btn.btn-primary{type: :button, data: { user: @user.screen_name }}= t('views.modal.group.create')
      .modal-footer
        %button.btn.btn-primary{name: 'gm-save', type: :button, data: { dismiss: :modal }}= t 'views.actions.done'

app/views/user/_modal_privileges_item.html.haml
- description ||= ''
%li.list-group-item{id: "privilege-#{privilege}"}
  .media
    .pull-left.j2-table
      %input.input--center{type: :checkbox, name: 'check-your-privileges', data: { type: privilege, user: user.screen_name }, checked: user.send("#{privilege}?"), autocomplete: 'off'}
    .media-body
      .list-group-item-heading= privilege.capitalize
      - unless description.blank?
        .list-group-item-text.text-muted= description

app/views/user/_profile.haml
.card.profile#profile
  .d-flex.d-sm-block
    %img.profile__avatar{ src: user.profile_picture.url(:large) }
    .profile__name-container
      .profile__name
        - unless user.profile.display_name.blank?
          .profile__display-name
            = user.profile.display_name
        .profile__screen-name
          = user.screen_name
  .card-body
    .profile__badge-container
      - if user.banned?
        %span.badge.badge-dark
          %i.fa.fa-fw.fa-ban
          = t(".badge.banned")
      - if user.following? current_user
        .badge.badge-light
          = t(".badge.follows_you")
      - if user_signed_in? && current_user.has_role?(:administrator)
        - if user.has_role?(:administrator)
          %span.badge.badge-danger
            %i.fa.fa-fw.fa-flask
            = t(".badge.admin")
        - if user.has_role?(:moderator)
          %span.badge.badge-success
            %i.fa.fa-fw.fa-users
            = t(".badge.moderator")
    - unless user.profile.description.blank?
      .profile__biography
        = markdown user.profile.description
    - unless user.profile.website.blank?
      .profile__website
        %i.fa.fa-fw.fa-globe
        %a{ href: user.profile.website, target: "_blank", rel: "nofollow" }= user.profile.display_website
    - unless user.profile.location.blank?
      .profile__location
        %i.fa.fa-fw.fa-location-arrow
        = user.profile.location
    = render "user/actions", user: user, type: :follower

app/views/user/_settings_tabs.html.haml
.col-md-3.col-xs-12.col-sm-4
  .panel.panel-default
    .list-group
      = list_group_item t('views.settings.tabs.account'), edit_user_registration_path
      = list_group_item t('views.settings.tabs.profile'), edit_user_profile_path
      = list_group_item t('views.settings.tabs.privacy'), edit_user_privacy_path
      = list_group_item t('views.settings.tabs.sharing'), services_path
      = list_group_item 'Theme', edit_user_theme_path
      = list_group_item "Your Data", user_data_path
      = list_group_item 'Export', user_export_path

  .hidden-xs= render "shared/links"

app/views/user/_stats.html.haml
.panel.panel-default.profile--panel#profile-stats
  .panel-heading
    %h3.panel-title Stats
  .panel-body
    .row
      %a{href: show_user_followers_path(@user.screen_name)}
        .col-md-6.col-sm-6.col-xs-6
          %h4.entry-text#follower-count= @user.follower_count
          %h6.entry-subtext= t('views.general.follower').pluralize(@user.follower_count)
      %a{href: show_user_friends_path(@user.screen_name)}
        .col-md-6.col-sm-6.col-xs-6
          %h4.entry-text#friend-count= @user.friend_count
          %h6.entry-subtext= t('views.general.following')
    .row
      %a{href: show_user_questions_path(@user.screen_name)}
        .col-md-6.col-sm-6.col-xs-6
          %h4.entry-text#asked-count= @user.asked_count
          %h6.entry-subtext= t('views.general.question').pluralize(@user.asked_count)
      %a{href: show_user_profile_path(@user.screen_name)}
        .col-md-6.col-sm-6.col-xs-6
          %h4.entry-text#answered-count= @user.answered_count
          %h6.entry-subtext= t('views.general.answer').pluralize(@user.answered_count)

app/views/user/show.html.haml
%div{ data: { controller: "navigation" } }
  %button.d-none{ data: { hotkey: "j", action: "navigation#down" } }
  %button.d-none{ data: { hotkey: "k", action: "navigation#up" } }
  #pinned-answers
    - @pinned_answers.each do |a|
      = render "answerbox", a:

  #answers
    - if @answers.empty?
      = render "shared/empty", icon: "fa-regular fa-comments", translation_key: ".user.answers"

    - @answers.each do |a|
      = render "answerbox", a:

- if @more_data_available
  .d-flex.justify-content-center.justify-content-sm-start#paginator
    = button_to t("voc.load"), user_path(@user),
      class: "btn btn-light",
      method: :get,
      params: { last_id: @answers_last_id },
      data: { controller: :hotkey, hotkey: "." },
      form: { data: { turbo_stream: true } }

:ruby
  provide(:title, user_title(@user))
  provide(:og, user_opengraph(@user))
  provide(:meta, user_twitter_card(@user))
  parent_layout 'user/profile'